//----------------------
// <auto-generated>
//    Generated by T4FluentNH.
// </auto-generated>
//----------------------
// ReSharper disable All
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using FluentNHibernate.Automapping;
using FluentNHibernate.Mapping;
using T4FluentNH.Metadata;
using NHibernate;
using NHibernate.Collection;
using NHibernate.Util;
using System.Threading.Tasks;
//<EntityProjectItem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><EntityFullName>T4FluentNH.Tests.Inheritance.Animal</EntityFullName><EntityFilePaths><string>Inheritance\Animal.cs</string></EntityFilePaths><OverrideFilePaths /><GeneratedFilePath>Animal.generated.cs</GeneratedFilePath></EntityProjectItem>
namespace T4FluentNH.Tests.Inheritance
{
    [GeneratedCode("T4Template", "1.0")]
    public partial class Animal
    {

        #region RelationsMetadata
        #pragma warning disable

        public new static readonly Dictionary<string, RelationMetadata> RelationsMetadata =
            new Dictionary<string, RelationMetadata>
            {
                {"Owner", new ManyToOneRelationMetadata
                {
                    RelatedModelType = typeof(Owner),
                    RelatedModelIdProperty = typeof(Owner).GetProperty("Id"),
                    AssociationType = AssociationType.Unidirectional,
                    Field = typeof(Animal).GetField("_owner", BindingFlags.Instance | BindingFlags.NonPublic),
                    ParameterName = "owner",
                    Property = typeof(Animal).GetProperty("Owner"),
                    SyntheticProperty = typeof(Animal).GetProperty("OwnerId"),
                    SyntheticField = typeof(Animal).GetField("_ownerId", BindingFlags.Instance | BindingFlags.NonPublic),
                    SyntheticPropertyMaxLength = null,
                    IsSyntheticPropertyTypeRequired = false,
                    
                }},
        
            };
        #pragma warning restore
        #endregion

        #region Owner

        private Owner _owner;

        [ReadOnly(true)]
        public virtual int? OwnerId 
        {
            get 
            {
                if(_isOwnerIdSet) return _ownerId;
                return Owner == null ? default(int?) : Owner.Id;
            }
            set 
            {
                _isOwnerIdSet = true;
                _ownerId = value; 
            }
        }

        private int? _ownerId;

        private bool _isOwnerIdSet = false;

        #endregion


        private void ResetField<T>(ref T field, T value, ref bool synthIsSetField)
        {
            field = value;
            synthIsSetField = false;
        }
    }
}
