//----------------------
// <auto-generated>
//    Generated by T4FluentNH.
// </auto-generated>
//----------------------
// ReSharper disable All
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using FluentNHibernate.Automapping;
using FluentNHibernate.Mapping;
using T4FluentNH.Metadata;
using NHibernate;
using NHibernate.Collection;
using NHibernate.Util;
using System.Threading.Tasks;
//<EntityProjectItem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><EntityFullName>T4FluentNH.Tests.EntityTypes.ETCodeListEntity</EntityFullName><EntityFilePaths><string>EntityTypes\ETCodeListEntity.cs</string></EntityFilePaths><OverrideFilePaths><string>EntityTypes\ETCodeListEntity.cs</string></OverrideFilePaths><GeneratedFilePath>ETCodeListEntity.generated.cs</GeneratedFilePath></EntityProjectItem>
namespace T4FluentNH.Tests.EntityTypes
{
    [GeneratedCode("T4Template", "1.0")]
    public partial class ETCodeListEntity
    {

        #region RelationsMetadata
        #pragma warning disable

        public new static readonly Dictionary<string, RelationMetadata> RelationsMetadata =
            new Dictionary<string, RelationMetadata>
            {
                {"SimpleEntity", new ManyToOneRelationMetadata
                {
                    RelatedModelType = typeof(ETSimpleEntity),
                    RelatedModelIdProperty = typeof(ETSimpleEntity).GetProperty("Id"),
                    AssociationType = AssociationType.Unidirectional,
                    Field = typeof(ETCodeListEntity).GetField("_simpleEntity", BindingFlags.Instance | BindingFlags.NonPublic),
                    ParameterName = "simpleEntity",
                    Property = typeof(ETCodeListEntity).GetProperty("SimpleEntity"),
                    SyntheticProperty = typeof(ETCodeListEntity).GetProperty("SimpleEntityId"),
                    SyntheticField = typeof(ETCodeListEntity).GetField("_simpleEntityId", BindingFlags.Instance | BindingFlags.NonPublic),
                    SyntheticPropertyMaxLength = null,
                    IsSyntheticPropertyTypeRequired = false,
                    
                }},
        
            };
        #pragma warning restore
        #endregion

        #region SimpleEntity

        private ETSimpleEntity _simpleEntity;

        [ReadOnly(true)]
        public virtual int? SimpleEntityId 
        {
            get 
            {
                if(_isSimpleEntityIdSet) return _simpleEntityId;
                return SimpleEntity == null ? default(int?) : SimpleEntity.Id;
            }
            set 
            {
                _isSimpleEntityIdSet = true;
                _simpleEntityId = value; 
            }
        }

        private int? _simpleEntityId;

        private bool _isSimpleEntityIdSet = false;

        #endregion


        private void ResetField<T>(ref T field, T value, ref bool synthIsSetField)
        {
            field = value;
            synthIsSetField = false;
        }
    }
}
