//----------------------
// <auto-generated>
//	Generated by T4FluentNH.
// </auto-generated>
//----------------------
// ReSharper disable All
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using FluentNHibernate.Automapping;
using T4FluentNH.Metadata;
//<EntityProjectItem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><EntityFullName>T4FluentNH.Tests.External.ExtVersionedEntity</EntityFullName><EntityFilePaths><string>External\ExtVersionedEntity.cs</string></EntityFilePaths><OverrideFilePaths /><GeneratedFilePath>ExtVersionedEntity.generated.cs</GeneratedFilePath></EntityProjectItem>
namespace T4FluentNH.Tests.External
{
	[GeneratedCode("T4Template", "1.0")]
	public partial class ExtVersionedEntity
	{

		#region RelationsMetadata
		#pragma warning disable

		public new static readonly Dictionary<string, RelationMetadata> RelationsMetadata =
            new Dictionary<string, RelationMetadata>
            {
                {"CreatedBy", new ManyToOneRelationMetadata
                {
					RelatedModelType = typeof(T4FluentNH.Domain.User),
					RelatedModelIdProperty = typeof(T4FluentNH.Domain.User).GetProperty("Id"),
					AssociationType = AssociationType.Unidirectional,
					Field = typeof(ExtVersionedEntity).GetField("_createdBy", BindingFlags.Instance | BindingFlags.NonPublic),
					ParameterName = "createdBy",
					Property = typeof(ExtVersionedEntity).GetProperty("CreatedBy"),
					SyntheticProperty = typeof(ExtVersionedEntity).GetProperty("CreatedById"),
					SyntheticField = typeof(ExtVersionedEntity).GetField("_createdById", BindingFlags.Instance | BindingFlags.NonPublic),
					SyntheticPropertyMaxLength = null,
					IsSyntheticPropertyTypeRequired = false,
					
                }},
		
            };
		#pragma warning restore
		#endregion

		#region CreatedBy

        private T4FluentNH.Domain.User _createdBy;

        [ReadOnly(true)]
		public virtual int? CreatedById 
		{
            get 
            {
                if(_isCreatedByIdSet) return _createdById;
                return CreatedBy == null ? default(int?) : CreatedBy.Id;
            }
            set 
            {
                _isCreatedByIdSet = true;
                _createdById = value; 
            }
		}

		private int? _createdById;

        private bool _isCreatedByIdSet = false;

		#endregion


		private void ResetField<T>(ref T field, T value, ref bool synthIsSetField)
        {
            field = value;
            synthIsSetField = false;
        }
	}
}
