//----------------------
// <auto-generated>
//	Generated by T4FluentNH.
// </auto-generated>
//----------------------
// ReSharper disable All
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using FluentNHibernate.Automapping;
using T4FluentNH.Metadata;
//<EntityProjectItem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><EntityFullName>T4FluentNH.Tests.ManyToOne.M2OPerson2</EntityFullName><EntityFilePaths><string>ManyToOne\M2OPerson2.cs</string></EntityFilePaths><OverrideFilePaths /><GeneratedFilePath>M2OPerson2.generated.cs</GeneratedFilePath></EntityProjectItem>
namespace T4FluentNH.Tests.ManyToOne
{
	[GeneratedCode("T4Template", "1.0")]
	public partial class M2OPerson2
	{

		#region RelationsMetadata
		#pragma warning disable

		public new static readonly Dictionary<string, RelationMetadata> RelationsMetadata =
            new Dictionary<string, RelationMetadata>
            {
                {"Car", new ManyToOneRelationMetadata
                {
					RelatedModelType = typeof(M2OCar2),
					RelatedModelIdProperty = typeof(M2OCar2).GetProperty("Id"),
					AssociationType = AssociationType.Unidirectional,
					Field = typeof(M2OPerson2).GetField("_car", BindingFlags.Instance | BindingFlags.NonPublic),
					ParameterName = "car",
					Property = typeof(M2OPerson2).GetProperty("Car"),
					SyntheticProperty = typeof(M2OPerson2).GetProperty("CarId"),
					SyntheticField = typeof(M2OPerson2).GetField("_carId", BindingFlags.Instance | BindingFlags.NonPublic),
					SyntheticPropertyMaxLength = null,
					IsSyntheticPropertyTypeRequired = false,
					
                }},
		
            };
		#pragma warning restore
		#endregion

		#region Car

        private M2OCar2 _car;

        [ReadOnly(true)]
		public virtual int? CarId 
		{
            get 
            {
                if(_isCarIdSet) return _carId;
                return Car == null ? default(int?) : Car.Id;
            }
            set 
            {
                _isCarIdSet = true;
                _carId = value; 
            }
		}

		private int? _carId;

        private bool _isCarIdSet = false;

		#endregion


		private void ResetField<T>(ref T field, T value, ref bool synthIsSetField)
        {
            field = value;
            synthIsSetField = false;
        }
	}
}
