//----------------------
// <auto-generated>
//    Generated by T4FluentNH.
// </auto-generated>
//----------------------
// ReSharper disable All
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using FluentNHibernate.Automapping;
using FluentNHibernate.Mapping;
using T4FluentNH.Metadata;
using NHibernate;
using NHibernate.Collection;
using NHibernate.Util;
using System.Threading.Tasks;
//<EntityProjectItem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><EntityFullName>T4FluentNH.Tests.OneToMany.O2MPerson</EntityFullName><EntityFilePaths><string>OneToMany\O2MPerson.cs</string></EntityFilePaths><OverrideFilePaths><string>OneToMany\O2MPerson.cs</string></OverrideFilePaths><GeneratedFilePath>O2MPerson.generated.cs</GeneratedFilePath></EntityProjectItem>
namespace T4FluentNH.Tests.OneToMany
{
    [GeneratedCode("T4Template", "1.0")]
    public partial class O2MPerson
    {

        #region RelationsMetadata
        #pragma warning disable

        public new static readonly Dictionary<string, RelationMetadata> RelationsMetadata =
            new Dictionary<string, RelationMetadata>
            {
                {"Cars", new OneToManyRelationMetadata
                {
                    RelatedModelType = typeof(O2MCar),
                    RelatedModelProperty = typeof(O2MCar).GetProperty("Owner"),
                    RelatedModelIdProperty = typeof(O2MCar).GetProperty("Id"),
                    AssociationType = AssociationType.Bidirectional,
                    Field = typeof(O2MPerson).GetField("_cars", BindingFlags.Instance | BindingFlags.NonPublic),
                    ParameterName = "car",
                    Property = typeof(O2MPerson).GetProperty("Cars"),
                    AddMethod = typeof(O2MPerson).GetMethods().FirstOrDefault(o => o.Name == "AddCar" && o.GetParameters().Length == 1 && o.GetParameters()[0].ParameterType == typeof(O2MCar)),
                    RemoveMethod = typeof(O2MPerson).GetMethods().FirstOrDefault(o => o.Name == "RemoveCar" && o.GetParameters().Length == 1 && o.GetParameters()[0].ParameterType == typeof(O2MCar)),
                    CollectionMapType = CollectionMapType.Unknown,
                    
                }},
        
            };
        #pragma warning restore
        #endregion

        #region Cars

        private ISet<O2MCar> _cars;

        public virtual void AddCar(O2MCar car)
        {
            this.AddOneToMany(o => o.Cars, car, o => o.Owner, o=> o.RemoveCar);
        }

        public virtual Task AddCarAsync(O2MCar car)
        {
            return this.AddOneToManyAsync(o => o.Cars, car, o => o.Owner, o=> o.RemoveCarAsync);
        }

        public virtual void RemoveCar(O2MCar car)
        {
            this.RemoveOneToMany(o => o.Cars, car, o => o.Owner);
        }

        public virtual Task RemoveCarAsync(O2MCar car)
        {
            return this.RemoveOneToManyAsync(o => o.Cars, car, o => o.Owner);
        }

        #endregion


        private void ResetField<T>(ref T field, T value, ref bool synthIsSetField)
        {
            field = value;
            synthIsSetField = false;
        }
    }
}
